Predicting House price based on the area of house, no. of bedrooms and the age of the house. The prediction will be done for :   

3000 sqr ft area, 3 bedrooms, 40 year old  
2500 sqr ft area, 4 bedrooms, 5 year old

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import linear_model

In [4]:
df=pd.read_csv('homeprices.csv')

In [5]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [6]:
df.shape

(6, 4)

In [7]:
#We will first fill the NaN value with the median of the column
df.bedrooms.median()

4.0

In [8]:
df.bedrooms=df.bedrooms.fillna(df.bedrooms.median())

In [9]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
reg=linear_model.LinearRegression()

In [11]:
x=df[['area','bedrooms','age']]
y=df['price']

In [12]:
reg.fit(x,y)

LinearRegression()

In [13]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [14]:
reg.intercept_

221323.00186540396

Predicting for 3000 sqr ft area, 3 bedrooms, 40 year old

In [15]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [16]:
#Manually calculating
print(221323.00186540396+112.06244194*3000+23388.88007794*3-3231.71790863*40)

498408.25157402386


Predicting for 2500 sqr ft area, 4 bedrooms, 5 year old

In [17]:
reg.predict([[2500,4,5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [18]:
#Manually calculating
print(221323.00186540396+112.06244194*2500+23388.88007794*4-3231.71790863*5)

578876.0374840139
