Predicting Salary based on the experience, test score and interview score. The prediction will be done for :   
2 yr experience, 9 test score, 6 interview score  
12 yr experience, 10 test score, 10 interview score

In [17]:
#Installing word2number library
!pip install word2number

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5569 sha256=a54c80db207a44deef454cce904bc0c82ffb588db3837904e80dc32cfa57d7ed
  Stored in directory: /root/.cache/pip/wheels/84/ff/26/d3cfbd971e96c5aa3737ecfced81628830d7359b55fbb8ca3b
Successfully built word2number


In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import linear_model
import math
from word2number import w2n

In [2]:
df=pd.read_csv('hiring.csv')

In [3]:
df.shape

(8, 4)

In [4]:
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [5]:
#We will fill the NaN values of experience as Zero(0)
df.experience=df.experience.fillna('zero')

In [6]:
df

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [7]:
#We will NaN value of test_score with Mean of the column
test_mean=df.test_score.mean()

In [8]:
test_mean

7.857142857142857

In [11]:
df.test_score=df.test_score.fillna(math.floor(test_mean))

In [12]:
df

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         7.0                7   72000
7     eleven         7.0                8   80000

In [19]:
df.experience=df.experience.apply(w2n.word_to_num)

In [20]:
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         7.0                7   72000
7          11         7.0                8   80000

In [22]:
reg=linear_model.LinearRegression()

In [23]:
x=df[['experience','test_score','interview_score']]
y=df['salary']

In [24]:
reg.fit(x,y)

LinearRegression()

In [25]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [26]:
reg.intercept_

14992.65144669314

Predicting for 2 yr experience, 9 test score, 6 interview score

In [27]:
reg.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [28]:
#Manually calculating
print(14992.65144669314+2922.26901502*2+2221.30909959*9+2147.48256637*6)

53713.86677126314


Predicting for 12 yr experience, 10 test score, 10 interview score

In [29]:
reg.predict([[12,10,10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])

In [30]:
#Manually calculating
print(14992.65144669314+2922.26901502*12+2221.30909959*10+2147.48256637*10)

93747.79628653315
